name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: licanseid

      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Build docs
        run: |
          pushd licenseid
          v doc -f html -m .
          ln -s _docs/licenseid.html _docs/index.html
          ls -alFh _docs/
          popd

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: licenseid/_docs/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
