name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs
        run: |
          wget -q https://github.com/vlang/v/releases/latest/download/v_linux.zip -O /tmp/v_linux.zip
          unzip -q /tmp/v_linux.zip -d /tmp
          /tmp/v/v doc -m . -f html -o doc/
          ln -s doc/licenseid.html doc/index.html
          ls -alFh doc/

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
